In [1]:
import os

if os.getcwd().endswith("notebooks"):
    os.chdir("..")

In [2]:
import ropes_league

In [3]:
data = ropes_league.IndividualLeagueData.from_env()

In [4]:
climbers = data.climbers()
climbers

,timestamp,name,email,division,paid
0,1/29/2024 13:42:03,Joseph M.,jmiller1305@gmail.com,Lead,TRUE
2,1/30/2024 20:36:24,Stephanie R.,stephanierodriguez16481@gmail.com,Top Rope,TRUE
3,1/31/2024 9:41:57,"Row K,",rebecca27kiefer@gmail.com,Top Rope,TRUE
4,1/31/2024 13:43:48,Jacob W.,jakewillner@gmail.com,Lead,TRUE
5,1/31/2024 14:23:42,Katia S.,katsidlosca@gmail.com,Top Rope,TRUE
7,2/6/2024 7:26:58,Suzy S.,suzanne.sharpe94@gmail.com,Top Rope,TRUE
10,2/7/2024 15:17:01,Joseph H.,traddad47@gmail.com,Lead,TRUE
11,2/7/2024 15:52:59,Tania,taniamsk5@gmail.com,Top Rope,TRUE
12,2/8/2024 13:28:09,Grayson H.,grayson.hild@gmail.com,Lead,TRUE
13,2/8/2024 13:45:03,Jacob H.,jacobholler.photo@gmail.com,Lead,TRUE
14,2/8/2024 15:17:28,Katie B.K.,kbentkoerick@gmail.com,Top Rope,TRUE
15,2/11/2024 9:47:31,Josh M.,mathewsjoshua14@gmail.com,Lead,TRUE
17,2/11/2024 22:06:07,Adrienne D.,asphyxiation143@gmail.com,Top Rope,TRUE
18,2/11/2024 22:08:00,Zsolt B.,zsbendel@hotmail.com,Top Rope,TRUE
19,,Zack D.,hello@zackdrescher.com,,TRUE
20,,Steve M.,info@stevenjohnminer.com,,TRUE
22,,Cullen F.,ccgfairchild@gmail.com,,TRUE
24,,Jacob P.E.,jacob@jpolev.com,,TRUE
25,,Tess D.,twdonovan7@gmail.com,,TRUE
26,,Abby A.,avitalabigail@gmail.com,,TRUE

In [5]:
climbs = data.climbs(1)
climbs

,timestamp,name,email,grade_1,rope_1,grade_2,rope_2,grade_3,rope_3
0,2/15/2024 20:33:40,adrienne dalena,asphyxiation143@gmail.com,5.10+,Top Rope,5.11-,Top Rope,5.11,Top Rope
1,2/15/2024 20:45:19,Zsolt Bendel,zsbendel@hotmail.com,5.11-,Top Rope,5.11-,Top Rope,5.11-,Top Rope
2,2/15/2024 20:49:47,Tania,taniamsk5@gmail.com,5.9,Top Rope,5.9,Top Rope,5.8,Top Rope
3,2/15/2024 20:49:47,Suzy Sharpe,suzanne.sharpe94@gmail.com,5.11-,Top Rope,5.11,Top Rope,5.10+,Top Rope
4,2/15/2024 20:51:12,Row Kiefer,rebecca27kiefer@gmail.com,5.10-,Top Rope,5.9,Top Rope,5.9,Top Rope
5,2/15/2024 20:51:52,Stephanie Rodriguez,stephanierodriguez16481@gmail.com,5.10-,Top Rope,5.10-,Top Rope,5.9,Top Rope
6,2/15/2024 21:04:39,Cullen Fairchild,ccgfairchild@gmail.com,5.11,Top Rope,5.11+,Top Rope,5.11+,Top Rope
7,2/15/2024 21:05:42,Joseph Hung,traddad47@gmail.com,5.10+,Lead,5.11-,Lead,5.11-,Lead
8,2/15/2024 21:07:52,Joe Miller,jmiller1305@gmail.com,5.8,Lead,5.10-,Lead,5.10,Lead
9,2/15/2024 21:11:57,Zack,hello@zackdrescher.com,5.10-,Top Rope,5.8,Top Rope,X,Top Rope
10,2/15/2024 21:13:49,Jacob Polcyn-Evans,jacob@jpolev.com,5.10-,Top Rope,5.10-,Top Rope,5.10,Top Rope
11,2/15/2024 21:17:34,Abby Avital,avitalabigail@gmail.com,5.9,Lead,5.10,Lead,5.11-,Lead
12,2/15/2024 21:18:29,Tess Donovan,twdonovan7@gmail.com,5.9,Lead,5.10+,Lead,5.10,Lead
13,2/16/2024 14:43:15,Steven Miner,info@stevenjohnminer.com,5.11-,Lead,5.11,Lead,5.11+,Top Rope
14,2/16/2024 15:25:31,Jacob Willner,jakewillner@gmail.com,5.11-,Lead,5.11-,Lead,5.11-,Lead
15,2/16/2024 16:27:16,Katia,katsidlosca@gmail.com,5.9,Top Rope,5.10-,Top Rope,5.10,Top Rope
16,2/16/2024 18:11:05,Katie Bent-Koerick,kbentkoerick@gmail.com,5.8,Top Rope,5.8,Top Rope,5.10-,Top Rope
17,2/17/2024 12:29:56,Josh Mathews,mathewsjoshua14@gmail.com,5.10-,Lead,5.10,Lead,5.10,Lead
18,2/19/2024 23:36:49,Grayson Hild,grayson.hild@gmail.com,5.10,Top Rope,5.10,Lead,5.11-,Lead

In [6]:
# assert climbs.email.isin(climbers.email).all()

In [7]:
climbers

,timestamp,name,email,division,paid
0,1/29/2024 13:42:03,Joseph M.,jmiller1305@gmail.com,Lead,TRUE
2,1/30/2024 20:36:24,Stephanie R.,stephanierodriguez16481@gmail.com,Top Rope,TRUE
3,1/31/2024 9:41:57,"Row K,",rebecca27kiefer@gmail.com,Top Rope,TRUE
4,1/31/2024 13:43:48,Jacob W.,jakewillner@gmail.com,Lead,TRUE
5,1/31/2024 14:23:42,Katia S.,katsidlosca@gmail.com,Top Rope,TRUE
7,2/6/2024 7:26:58,Suzy S.,suzanne.sharpe94@gmail.com,Top Rope,TRUE
10,2/7/2024 15:17:01,Joseph H.,traddad47@gmail.com,Lead,TRUE
11,2/7/2024 15:52:59,Tania,taniamsk5@gmail.com,Top Rope,TRUE
12,2/8/2024 13:28:09,Grayson H.,grayson.hild@gmail.com,Lead,TRUE
13,2/8/2024 13:45:03,Jacob H.,jacobholler.photo@gmail.com,Lead,TRUE
14,2/8/2024 15:17:28,Katie B.K.,kbentkoerick@gmail.com,Top Rope,TRUE
15,2/11/2024 9:47:31,Josh M.,mathewsjoshua14@gmail.com,Lead,TRUE
17,2/11/2024 22:06:07,Adrienne D.,asphyxiation143@gmail.com,Top Rope,TRUE
18,2/11/2024 22:08:00,Zsolt B.,zsbendel@hotmail.com,Top Rope,TRUE
19,,Zack D.,hello@zackdrescher.com,,TRUE
20,,Steve M.,info@stevenjohnminer.com,,TRUE
22,,Cullen F.,ccgfairchild@gmail.com,,TRUE
24,,Jacob P.E.,jacob@jpolev.com,,TRUE
25,,Tess D.,twdonovan7@gmail.com,,TRUE
26,,Abby A.,avitalabigail@gmail.com,,TRUE

In [8]:
scores = data.scores(1)
scores

,name,email,grade_1,rope_1,grade_2,rope_2,grade_3,rope_3,score
15,Cullen F.,ccgfairchild@gmail.com,5.11,Top Rope,5.11+,Top Rope,5.11+,Top Rope,26
14,Steve M.,info@stevenjohnminer.com,5.11-,Lead,5.11,Lead,5.11+,Top Rope,26
3,Jacob W.,jakewillner@gmail.com,5.11-,Lead,5.11-,Lead,5.11-,Lead,24
6,Joseph H.,traddad47@gmail.com,5.10+,Lead,5.11-,Lead,5.11-,Lead,23
11,Adrienne D.,asphyxiation143@gmail.com,5.10+,Top Rope,5.11-,Top Rope,5.11,Top Rope,21
5,Suzy S.,suzanne.sharpe94@gmail.com,5.11-,Top Rope,5.11,Top Rope,5.10+,Top Rope,21
12,Zsolt B.,zsbendel@hotmail.com,5.11-,Top Rope,5.11-,Top Rope,5.11-,Top Rope,21
8,Grayson H.,grayson.hild@gmail.com,5.10,Top Rope,5.10,Lead,5.11-,Lead,19
18,Abby A.,avitalabigail@gmail.com,5.9,Lead,5.10,Lead,5.11-,Lead,18
17,Tess D.,twdonovan7@gmail.com,5.9,Lead,5.10+,Lead,5.10,Lead,17
10,Josh M.,mathewsjoshua14@gmail.com,5.10-,Lead,5.10,Lead,5.10,Lead,17
0,Joseph M.,jmiller1305@gmail.com,5.8,Lead,5.10-,Lead,5.10,Lead,14
16,Jacob P.E.,jacob@jpolev.com,5.10-,Top Rope,5.10-,Top Rope,5.10,Top Rope,13
4,Katia S.,katsidlosca@gmail.com,5.9,Top Rope,5.10-,Top Rope,5.10,Top Rope,12
1,Stephanie R.,stephanierodriguez16481@gmail.com,5.10-,Top Rope,5.10-,Top Rope,5.9,Top Rope,11
2,"Row K,",rebecca27kiefer@gmail.com,5.10-,Top Rope,5.9,Top Rope,5.9,Top Rope,10
7,Tania,taniamsk5@gmail.com,5.9,Top Rope,5.9,Top Rope,5.8,Top Rope,8
9,Katie B.K.,kbentkoerick@gmail.com,5.8,Top Rope,5.8,Top Rope,5.10-,Top Rope,8
13,Zack D.,hello@zackdrescher.com,5.10-,Top Rope,5.8,Top Rope,X,Top Rope,6

In [9]:
from ropes_league.league_data import climb_string


def week_results_string(scores_data):
    return "\n".join(
        [
            f"{i+1}. {row['name']} - {climb_string(row)} - {row['score']}"
            for i, row in scores_data.reset_index().iterrows()
        ]
    )

In [10]:
results = data.results(3).drop(columns='email')
results.to_csv("results.csv")
results

           name  score climb_1 climb_2 climb_3
1     Joseph H.     28   5.11L  5.12-L  5.11-L
2      Jacob W.     27   5.11L   5.11L   5.11+
3      Zsolt B.     22   5.11-    5.11   5.11-
4   Adrienne D.     21   5.11-   5.11-   5.11-
5       Suzy S.     19   5.10-   5.11-    5.11
6    Grayson H.     17   5.10L  5.10-L   5.10+
7    Jacob P.E.     17    5.10   5.11-    5.10
8         Tania     11     5.9     5.9    5.10
9    Katie B.K.     10     5.9     5.9   5.10-
10      Zack D.     10     5.9   5.10-     5.9

In [11]:
standings = data.standings(3).drop(columns='email')
standings.to_csv("standings.csv")
standings

    score  points_earned change          name
1    78.0           28.0     +2     Joseph H.
2    75.0           27.0     +2      Jacob W.
3    65.0           22.0     +4      Zsolt B.
4    64.0           21.0     +2   Adrienne D.
5    61.0           19.0     +3       Suzy S.
6    59.0           17.0     +3    Grayson H.
7    54.0            0.0     -6      Steve M.
8    53.0            0.0     -6     Cullen F.
9    45.0           17.0     +4    Jacob P.E.
10   44.0            0.0     -5       Tess D.
11   36.0            0.0     -1       Abby A.
12   34.0            0.0     -1       Josh M.
13   33.0            0.0     -1     Joseph M.
14   29.0           11.0     +3         Tania
15   25.0           10.0     +3       Zack D.
16   22.0            0.0     -2      Katia S.
17   21.0            0.0     -2  Stephanie R.
18   20.0            0.0     -2        Row K,
19   18.0           10.0      -    Katie B.K.