In [1]:
import os

if os.getcwd().endswith("notebooks"):
    os.chdir("..")

In [2]:
import ropes_league

In [3]:
data = ropes_league.LeagueData.from_env()

In [4]:
scores = data.season_scores().assign(
    top_diff=lambda df: df[["difficulty_1", "difficulty_2", "difficulty_3"]].max(axis=1),
    bot_diff=lambda df: df[["difficulty_1", "difficulty_2", "difficulty_3"]].min(axis=1),
    n_climbs=lambda df: df[["difficulty_1", "difficulty_2", "difficulty_3"]].count(axis=1)
)

In [5]:
scores

,team_id,climber_id,email,grade_1,rope_1,grade_2,rope_2,grade_3,rope_3,difficulty_1,...,climber_difficulty,points_1,points_2,points_3,points,week,team,top_diff,bot_diff,n_climbs
0,4,14,Stephanierodriguez16481@gmail.com,5.10,Top Rope,5.10-,Top Rope,5.10-,Top Rope,4,...,2,3.0,2.0,2.0,7.0,1,NaN,4.0,3.0,3
1,10,31,jonathan.pivovar@gmail.com,5.11,Top Rope,5.10+,Top Rope,5.10+,Top Rope,7,...,4,4.0,2.0,2.0,8.0,1,NaN,7.0,5.0,3
2,4,15,Rebecca27kiefer@gmail.com,5.10-,Top Rope,5.10-,Top Rope,5.10-,Top Rope,3,...,2,2.0,2.0,2.0,6.0,1,NaN,3.0,3.0,3
3,10,29,Cbombardo13@gmail.com,5.10-,Top Rope,5.10-,Top Rope,5.10+,Top Rope,3,...,3,1.0,1.0,3.0,5.0,1,NaN,5.0,3.0,3
4,7,26,Difengtan@gmail.com,5.10,Top Rope,5.10+,Top Rope,5.10,Top Rope,4,...,4,1.0,2.0,1.0,4.0,1,NaN,5.0,4.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,5,18,jihye.hah@gmail.com,5.10+,Top Rope,5.10+,Top Rope,5.10,Top Rope,5,...,4,2.0,2.0,1.0,5.0,6,Ain't Nobody Beta ¯\_(ツ)_/¯,5.0,4.0,3
153,5,17,Pomaquero.dennis@gmail.com,5.10+,Top Rope,5.10+,Top Rope,5.10,Top Rope,5,...,3,3.0,3.0,2.0,8.0,6,Ain't Nobody Beta ¯\_(ツ)_/¯,5.0,4.0,3
154,1,1,hajder@aclanyc.com,5.10-,Top Rope,5.10,Top Rope,5.10,Top Rope,3,...,3,1.0,2.0,2.0,5.0,6,Team Head Empty 🤠,4.0,3.0,3
155,7,24,yu.logan@gmail.com,5.11,Top Rope,5.11-,Top Rope,5.10+,Top Rope,7,...,4,4.0,3.0,2.0,9.0,6,"Leave the rope, take the cannoli ❄️",7.0,5.0,3
156,7,25,Jess.jonesr@gmail.com,5.9,Top Rope,5.10,Top Rope,5.10,Top Rope,2,...,2,1.0,3.0,3.0,7.0,6,"Leave the rope, take the cannoli ❄️",4.0,2.0,3

In [6]:
climbers = data.climbers().assign(
    points=scores.groupby("climber_id").points.sum(),
    nights=scores.groupby("climber_id").points.count(),
    top_diff=scores.groupby("climber_id").top_diff.max(),
    bot_diff=scores.groupby("climber_id").bot_diff.min(),
    top_grade=lambda df: df.top_diff.replace(
        {v: k for k, v in ropes_league.league_data.GRADE_DIFFICULTY.items()}
    ),
    bot_grade=lambda df: df.bot_diff.replace(
        {v: k for k, v in ropes_league.league_data.GRADE_DIFFICULTY.items()}
    ),
    diff_diff=lambda df: df.top_diff - df.bot_diff,
    best_week_score=scores.groupby("climber_id").points.max(),
    best_week=scores.loc[scores.groupby("climber_id").points.idxmax()].week.reset_index(
        drop=True
    ),
    n_climbs=scores.groupby("climber_id").n_climbs.sum(),
)

In [7]:
climbers

,name,email,grade,team,difficulty,points,nights,top_diff,bot_diff,top_grade,bot_grade,diff_diff,best_week_score,best_week,n_climbs
id,,,,,,,,,,,,,,,
0,Alan Hajder,alanhajder@gmail.com,5.10+,1,5,42.0,6.0,8.0,5.0,5.11+,5.10+,3.0,10.0,6.0,16.0
1,Izabela Hajder,hajder@aclanyc.com,5.10-,1,3,36.0,6.0,6.0,3.0,5.11-,5.10-,3.0,7.0,1.0,17.0
2,Matt Keim,mattkeim009@gmail.com,5.10+,1,5,23.0,4.0,8.0,5.0,5.11+,5.10+,3.0,7.0,1.0,12.0
3,Carlos Garcia,blackstone264@gmail.com,5.10,1,4,23.0,6.0,5.0,4.0,5.10+,5.10,1.0,5.0,3.0,16.0
4,Matt Cianfrani,Matt@cianfranifilms.com,5.10,2,4,33.5,5.0,8.0,4.0,5.11+,5.10,4.0,14.5,1.0,15.0
5,Amanda Jenkins,Amandajnyc@gmail.com,5.10-,2,3,23.5,4.0,5.0,3.0,5.10+,5.10-,2.0,8.0,6.0,12.0
6,Daria Huxley,dariahuxley@gmail.com,5.9,2,2,15.0,2.0,4.0,2.0,5.10,5.9,2.0,9.5,4.0,6.0
7,Jackson Jarvis,jacksonjarvis.dp@gmail.com,5.10-,2,3,5.0,1.0,4.0,3.0,5.10,5.10-,1.0,5.0,3.0,3.0
8,Zsolt Bendel,zsbendel@hotmail.com,5.10+,3,5,32.0,5.0,7.0,5.0,5.11,5.10+,2.0,8.0,4.0,15.0
9,Adrienne Dalena,Asphyxiation143@gmail.com,5.10,3,4,39.0,5.0,6.0,3.0,5.11-,5.10-,3.0,10.0,1.0,15.0
10,Liam Mcelheny,Liammcel@gmail.com,5.10+,3,5,35.5,5.0,7.0,5.0,5.11,5.10+,2.0,8.0,2.0,15.0
11,Clara Smith,clara@smithsaltzman.com,5.10-,3,3,28.5,4.0,5.0,2.0,5.10+,5.9,3.0,10.0,5.0,12.0
12,Jacob Willner,jakewillner@gmail.com,5.10+,4,5,38.0,6.0,7.0,4.0,5.11,5.10,3.0,9.0,5.0,18.0
13,Grayson,Grayson.hild@gmail.com,5.10,4,4,49.0,6.0,6.0,3.0,5.11-,5.10-,3.0,11.5,2.0,18.0
14,Stephanie Rodriguez,Stephanierodriguez16481@gmail.com,5.9,4,2,44.0,6.0,4.0,3.0,5.10,5.10-,1.0,8.0,4.0,18.0
15,Row Kiefer,Rebecca27kiefer@gmail.com,5.9,4,2,41.5,6.0,4.0,3.0,5.10,5.10-,1.0,7.5,6.0,18.0
16,Sebastian Jungschaffer,jungschaffer@gmail.com,5.10,5,4,38.0,6.0,6.0,4.0,5.11-,5.10,2.0,7.0,2.0,18.0
17,Dennis Pomaquero,Pomaquero.dennis@gmail.com,5.10-,5,3,42.0,5.0,6.0,4.0,5.11-,5.10,2.0,9.0,2.0,15.0
18,Jihye Hah,jihye.hah@gmail.com,5.10,5,4,25.0,5.0,6.0,4.0,5.11-,5.10,2.0,7.0,4.0,15.0
19,Katia Sidlosca,katsidlosca@gmail.com,5.9,5,2,27.0,4.0,5.0,2.0,5.10+,5.9,3.0,9.0,4.0,12.0
20,Christopher Randall,christopherjoelrandall@gmail.com,5.10+,6,5,NaN,NaN,NaN,NaN,X,X,NaN,NaN,2.0,NaN
21,Dakota Bowman,Dakotabowman11@yahoo.com,5.10+,6,5,NaN,NaN,NaN,NaN,X,X,NaN,NaN,2.0,NaN
22,Luciana Torres,Luciana.p.torres@gmail.com,5.10+,6,5,41.0,4.0,7.0,5.0,5.11,5.10+,2.0,12.0,3.0,12.0
23,Jiayin Zhang,Jz4021@nyu.edu,5.9,6,2,20.0,3.0,4.0,2.0,5.10,5.9,2.0,7.0,1.0,9.0
24,Loganyu,yu.logan@gmail.com,5.10,7,4,49.0,6.0,7.0,4.0,5.11,5.10,3.0,10.0,3.0,18.0
25,Jess Jones,Jess.jonesr@gmail.com,5.9,7,2,44.0,6.0,4.0,2.0,5.10,5.9,2.0,11.0,6.0,18.0
26,Di Tan,Difengtan@gmail.com,5.10+,7,5,43.0,6.0,8.0,4.0,5.11+,5.10,4.0,10.0,5.0,18.0
27,Alex Dotterweich,alexdotterweich@gmail.com,5.10,7,4,37.0,6.0,7.0,4.0,5.11,5.10,3.0,9.0,6.0,18.0
28,Zack Drescher,Hello@zackdrescher.com,5.10-,10,3,35.0,5.0,5.0,2.0,5.10+,5.9,3.0,11.0,6.0,14.0
29,Castina Bombardo,cbombardo13@gmail.com,5.10-,10,3,22.0,5.0,5.0,3.0,5.10+,5.10-,2.0,7.0,2.0,12.0
30,Steven miner,Info@stevenjohnminer.com,5.11-,10,6,30.5,5.0,9.0,6.0,5.12-,5.11-,3.0,8.0,1.0,12.0
31,Jono Pivovar,jonathan.pivovar@gmail.com,5.10+,10,5,42.0,5.0,7.0,5.0,5.11,5.10+,2.0,11.0,1.0,15.0
32,Victoria fitzgerald,vfitzger21@gmail.com,5.10,,4,4.0,1.0,5.0,4.0,5.10+,5.10,1.0,4.0,6.0,3.0
33,Jake Leonard,jleo.nard218@gmail.com,5.10-,,3,16.0,2.0,5.0,4.0,5.10+,5.10,1.0,8.0,6.0,6.0
34,Kengo,Kikedaiy@gmail.com,5.10+,,5,30.0,5.0,8.0,5.0,5.11+,5.10+,3.0,8.0,NaN,12.0
35,Joshua Drubin,j.drubin94@gmail.com,5.11-,,6,4.0,1.0,7.0,7.0,5.11,5.11,0.0,4.0,NaN,2.0

# MVC

In [13]:
climbers.sort_values("points", ascending=False)[["name", "points"]]

                      name  points
id
13                Grayson     49.0
24                Loganyu     49.0
25              Jess Jones    44.0
14    Stephanie Rodriguez     44.0
26                  Di Tan    43.0
0              Alan Hajder    42.0
31            Jono Pivovar    42.0
17        Dennis Pomaquero    42.0
15              Row Kiefer    41.5
22         Luciana Torres     41.0
9          Adrienne Dalena    39.0
12           Jacob Willner    38.0
16  Sebastian Jungschaffer    38.0
27        Alex Dotterweich    37.0
1           Izabela Hajder    36.0
10           Liam Mcelheny    35.5
28           Zack Drescher    35.0
4           Matt Cianfrani    33.5
8             Zsolt Bendel    32.0
30            Steven miner    30.5
34                   Kengo    30.0
11             Clara Smith    28.5
19          Katia Sidlosca    27.0
18               Jihye Hah    25.0
5           Amanda Jenkins    23.5
3            Carlos Garcia    23.0
2                Matt Keim    23.0
29        Castina Bombardo    22.0
23            Jiayin Zhang    20.0
33            Jake Leonard    16.0
6             Daria Huxley    15.0
7           Jackson Jarvis     5.0
32    Victoria fitzgerald      4.0
35           Joshua Drubin     4.0
20     Christopher Randall     NaN
21           Dakota Bowman     NaN

# Attendence

In [16]:
climbers[climbers.nights == 6].name

id
0                Alan Hajder
1             Izabela Hajder
3              Carlos Garcia
12             Jacob Willner
13                  Grayson
14      Stephanie Rodriguez
15                Row Kiefer
16    Sebastian Jungschaffer
24                  Loganyu
25                Jess Jones
26                    Di Tan
27          Alex Dotterweich
Name: name, dtype: object

In [14]:
climbers.sort_values("nights", ascending=False)

                      name  nights
id
0              Alan Hajder     6.0
25              Jess Jones     6.0
16  Sebastian Jungschaffer     6.0
15              Row Kiefer     6.0
14    Stephanie Rodriguez      6.0
13                Grayson      6.0
12           Jacob Willner     6.0
24                Loganyu      6.0
26                  Di Tan     6.0
27        Alex Dotterweich     6.0
3            Carlos Garcia     6.0
1           Izabela Hajder     6.0
18               Jihye Hah     5.0
28           Zack Drescher     5.0
29        Castina Bombardo     5.0
30            Steven miner     5.0
31            Jono Pivovar     5.0
34                   Kengo     5.0
17        Dennis Pomaquero     5.0
10           Liam Mcelheny     5.0
9          Adrienne Dalena     5.0
8             Zsolt Bendel     5.0
4           Matt Cianfrani     5.0
19          Katia Sidlosca     4.0
22         Luciana Torres      4.0
11             Clara Smith     4.0
5           Amanda Jenkins     4.0
2                Matt Keim     4.0
23            Jiayin Zhang     3.0
6             Daria Huxley     2.0
33            Jake Leonard     2.0
7           Jackson Jarvis     1.0
32    Victoria fitzgerald      1.0
35           Joshua Drubin     1.0
20     Christopher Randall     NaN
21           Dakota Bowman     NaN

# Top Nights

In [17]:
climbers.sort_values("best_week_score", ascending=False)[["name", "best_week_score", "best_week"]]

                      name  best_week_score  best_week
id
4           Matt Cianfrani             14.5        1.0
22         Luciana Torres              12.0        3.0
13                Grayson              11.5        2.0
31            Jono Pivovar             11.0        1.0
28           Zack Drescher             11.0        6.0
25              Jess Jones             11.0        6.0
0              Alan Hajder             10.0        6.0
26                  Di Tan             10.0        5.0
9          Adrienne Dalena             10.0        1.0
24                Loganyu              10.0        3.0
11             Clara Smith             10.0        5.0
6             Daria Huxley              9.5        4.0
19          Katia Sidlosca              9.0        4.0
27        Alex Dotterweich              9.0        6.0
17        Dennis Pomaquero              9.0        2.0
12           Jacob Willner              9.0        5.0
33            Jake Leonard              8.0        6.0
14    Stephanie Rodriguez               8.0        4.0
10           Liam Mcelheny              8.0        2.0
8             Zsolt Bendel              8.0        4.0
5           Amanda Jenkins              8.0        6.0
34                   Kengo              8.0        NaN
30            Steven miner              8.0        1.0
15              Row Kiefer              7.5        6.0
1           Izabela Hajder              7.0        1.0
18               Jihye Hah              7.0        4.0
23            Jiayin Zhang              7.0        1.0
16  Sebastian Jungschaffer              7.0        2.0
29        Castina Bombardo              7.0        2.0
2                Matt Keim              7.0        1.0
7           Jackson Jarvis              5.0        3.0
3            Carlos Garcia              5.0        3.0
32    Victoria fitzgerald               4.0        6.0
35           Joshua Drubin              4.0        NaN
20     Christopher Randall              NaN        2.0
21           Dakota Bowman              NaN        2.0

In [18]:
climbers.sort_values("top_diff", ascending=False)[["name", "top_grade", "top_diff"]]

                      name top_grade  top_diff
id
30            Steven miner     5.12-       9.0
0              Alan Hajder     5.11+       8.0
2                Matt Keim     5.11+       8.0
34                   Kengo     5.11+       8.0
4           Matt Cianfrani     5.11+       8.0
26                  Di Tan     5.11+       8.0
12           Jacob Willner      5.11       7.0
31            Jono Pivovar      5.11       7.0
27        Alex Dotterweich      5.11       7.0
24                Loganyu       5.11       7.0
22         Luciana Torres       5.11       7.0
35           Joshua Drubin      5.11       7.0
10           Liam Mcelheny      5.11       7.0
8             Zsolt Bendel      5.11       7.0
17        Dennis Pomaquero     5.11-       6.0
16  Sebastian Jungschaffer     5.11-       6.0
1           Izabela Hajder     5.11-       6.0
18               Jihye Hah     5.11-       6.0
9          Adrienne Dalena     5.11-       6.0
13                Grayson      5.11-       6.0
28           Zack Drescher     5.10+       5.0
3            Carlos Garcia     5.10+       5.0
33            Jake Leonard     5.10+       5.0
32    Victoria fitzgerald      5.10+       5.0
5           Amanda Jenkins     5.10+       5.0
29        Castina Bombardo     5.10+       5.0
11             Clara Smith     5.10+       5.0
19          Katia Sidlosca     5.10+       5.0
7           Jackson Jarvis      5.10       4.0
6             Daria Huxley      5.10       4.0
23            Jiayin Zhang      5.10       4.0
15              Row Kiefer      5.10       4.0
14    Stephanie Rodriguez       5.10       4.0
25              Jess Jones      5.10       4.0
20     Christopher Randall         X       NaN
21           Dakota Bowman         X       NaN

In [19]:
climbers.sort_values("diff_diff", ascending=False)[["name", "bot_grade", "top_grade", "diff_diff"]]

                      name bot_grade top_grade  diff_diff
id
4           Matt Cianfrani      5.10     5.11+        4.0
26                  Di Tan      5.10     5.11+        4.0
0              Alan Hajder     5.10+     5.11+        3.0
9          Adrienne Dalena     5.10-     5.11-        3.0
1           Izabela Hajder     5.10-     5.11-        3.0
24                Loganyu       5.10      5.11        3.0
13                Grayson      5.10-     5.11-        3.0
12           Jacob Willner      5.10      5.11        3.0
11             Clara Smith       5.9     5.10+        3.0
27        Alex Dotterweich      5.10      5.11        3.0
28           Zack Drescher       5.9     5.10+        3.0
30            Steven miner     5.11-     5.12-        3.0
34                   Kengo     5.10+     5.11+        3.0
2                Matt Keim     5.10+     5.11+        3.0
19          Katia Sidlosca       5.9     5.10+        3.0
22         Luciana Torres      5.10+      5.11        2.0
29        Castina Bombardo     5.10-     5.10+        2.0
31            Jono Pivovar     5.10+      5.11        2.0
25              Jess Jones       5.9      5.10        2.0
23            Jiayin Zhang       5.9      5.10        2.0
17        Dennis Pomaquero      5.10     5.11-        2.0
18               Jihye Hah      5.10     5.11-        2.0
16  Sebastian Jungschaffer      5.10     5.11-        2.0
10           Liam Mcelheny     5.10+      5.11        2.0
8             Zsolt Bendel     5.10+      5.11        2.0
6             Daria Huxley       5.9      5.10        2.0
5           Amanda Jenkins     5.10-     5.10+        2.0
15              Row Kiefer     5.10-      5.10        1.0
14    Stephanie Rodriguez      5.10-      5.10        1.0
7           Jackson Jarvis     5.10-      5.10        1.0
32    Victoria fitzgerald       5.10     5.10+        1.0
33            Jake Leonard      5.10     5.10+        1.0
3            Carlos Garcia      5.10     5.10+        1.0
35           Joshua Drubin      5.11      5.11        0.0
20     Christopher Randall         X         X        NaN
21           Dakota Bowman         X         X        NaN

In [20]:
climbers.columns

Index(['name', 'email', 'grade', 'team', 'difficulty', 'points', 'nights',
       'top_diff', 'bot_diff', 'top_grade', 'bot_grade', 'diff_diff',
       'best_week_score', 'best_week', 'n_climbs'],
      dtype='object')

                                name      emoji  points
id
1                   Team head empty           🤠      17
2              Power Bar Racing Team        ⚡️🍫      22
3        Boulder? I hardly know ‘er!                 21
4                           Teamtop           🏕      36
5                  Ain't Nobody Beta  ¯\_(ツ)_/¯      23
6                    Supple dumpers           🫠       6
7   Leave the rope, take the cannoli         ❄️      33
10        The New York Stock Brokers          📈      20

In [29]:
climbers.merge(
    data.teams().rename(columns={"name": "team_name"})[["team_name"]],
    how="left",
    left_on="team",
    right_index=True,
)[
    [
        "name",
        "team_name",
        "points",
        "nights",
        "top_grade",
        "bot_grade",
        "diff_diff",
        "best_week_score",
        "best_week",
        "n_climbs",
    ]
].to_csv("climbers.csv", index=False)

/home/zack/ropes-league/.venv/lib/python3.8/site-packages/pandas/core/internals/blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)